# Generated by Django 2.2.4 on 2019-08-29 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20190829_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='DVD',
            new_name='dvd',
        ),
    ]
