# Generated by Django 2.2.4 on 2019-08-29 19:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20190829_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rattings',
        ),
        migrations.AddField(
            model_name='movie',
            name='ratings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
