# Generated by Django 2.2.4 on 2019-08-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20190829_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='dvd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
